### ISSUE TITLE
不能实现手动造词

### ISSUE THREAD

**Issue by starwing** [ryan00zou/-#1]
你好~我用这套配置发现没有办法手动造词……按'的确会出现“手动造词”的提示，但是之后输入的任何字母都没有出现选单……比如输入'vh'xt'yz就直接这么显示了，没有任何词给我选……这应该怎么办呢？系统是Mac鼠须管，安装的方法是先安装了最新的Rime挂接词库，然后merge了flypy.schema.yaml文件，基本上只有几个按键绑定的区别，另外留下了flypy_top.txt，flypy_user.txt的相关配置，别的都是按照你的配置来的……

**Comment by pimgeek** [comment]
> 你好~我用这套配置发现没有办法手动造词……按'的确会出现“手动造词”的提示，但是之后输入的任何字母都没有出现选单……比如输入'vh'xt'yz就直接这么显示了……

@starwing 我折腾了 3 个多小时，终于实现了这个 **手动造词** 的效果，写个简单的操作说明，如果不管用我以后有空再更新这个说明

01. 先用小鹤官方网站的说明安装好原版的小鹤音形输入法，重新部署确保工作正常
02. 把本项目的三个 YAML 文件粘贴到 RIME 的用户配置文件夹，会覆盖掉一个原始的小鹤配置文件
03. 修改 `default.custom.yaml`，包含这两个选项：
```
patch:
  schema_list:
    - schema: flypy 
    - schema: flypyzc
```
04. 重新部署
05. 用 Ctrl + \` 切换到 Love Fly
06. 用 README 所说的方法输入单引号开始造词，这时是可以出汉字的，不会只出拼音
07. 一个最重要的细节——输入完一个新词以后，千万别立刻回退删除它，立刻再用小鹤的构词规则再打两次，就能变成正式的内置词语了。
08. 比如我想添加 `黄兴`，可以先输 `'hl'xkxb`，让这个词显示正确，然后按空格键上屏。
09. 这时注意千万不要删除这两个字，立刻用简单的音形码再输一次 `hlxk`，如果前面的步骤配置都正确，你会发现黄兴已经出现在内置词库的 **合理性** 词语后面，可能还带着☯️图标
10. 这时只要再重复打一遍 `hlxk` ，黄兴这个词就完全转正了，而且必须排列在系统内置词 `合理性` 的后面

**Comment by starwing** [comment]
@pimgeek 记得这么做以后再切回小鹤音形，因为Auto Flypy的一些词语和顺序和官方的还是不一样的。这么做以后小鹤音形也能造词的。另外最好不是覆盖flypy.schema.yaml，我用的是merge。

**Comment by pimgeek** [comment]
> @pimgeek 记得这么做以后再切回小鹤音形，因为Auto Flypy的一些词语和顺序和官方的还是不一样的。这么做以后小鹤音形也能造词的。另外最好不是覆盖flypy.schema.yaml，我用的是merge。

确实可以通过合并的方式启用，现在已经能够正常加词了，这样就能用上最新的小鹤官方设置。

**Comment by wongshg** [comment]
我想问下怎么merge呢？

**Comment by pimgeek** [comment]
> 我想问下怎么merge呢？

主要的部分是这样：

```yaml
schema:
  schema_id: flypy
  # 省略无关部分 ...

engine:
  segmentors:
    - affix_segmentor@udzc
    # 省略无关部分 ...
  translators:
    - table_translator@fixed
    - table_translator@zdzc
    - table_translator@udzc
    # 省略无关部分 ...

translator:
  dictionary: flypy
  enable_charset_filter: false
  enable_sentence: false
  enable_completion: false
  enable_user_dict: false
  disable_user_dict_for_patterns:
    - "^z.*$"

fixed:
  dictionary: flypyzc.extended
  enable_charset_filter: false
  enable_sentence: false
  enable_encoder: false
  enable_completion: false  # 编码提示开关
  encode_commit_history: false
  enable_user_dict: false
  initial_quality: 1
  disable_user_dict_for_patterns:
    - "^o.*$"
    - "^`.*$"

zdzc:
  __include: /fixed
  enable_encoder: true
  enable_user_dict: true
  encode_commit_history: false  # 开启/关闭自动造词功能：true/false。
  max_phrase_length: 4
  initial_quality: -1.5

udzc:
  __include: /fixed
  initial_quality: -1
  enable_sentence: true
  prefix: "'"
  tips: "〔手动造词〕"
  tag: udzc

recognizer:
  import_preset: default
  patterns:
    # 省略无关部分 ...
    udzc: "^[a-z]*'[a-z']*$"
    punct: ""

```

其中：`fixed:` 下方 `dictionary: flypyzc.extended` 对应文件 `flypyzc.extended.dict.yaml`

```yaml
---
name: flypyzc.extended
version: "0.1"
sort: original
import_tables:
  - flypyzc

encoder:
  exclude_patterns:
    - '^o.*$'
    - '^`.*$'
  rules:
    - length_equal: 2
      formula: "AaAbBaBb"
    - length_equal: 3
      formula: "AaBaCaCb"
    - length_in_range: [4, 10]
      formula: "AaBaCaZa"
...

```

其中 `import_tables:` 下方的 `flypyzc` 对应文件 `flypyzc.dict.yaml`

```yaml
---
name: flypyzc
version: "0.1"
sort: original

encoder:
  exclude_patterns:
    - '^o.*$'
    - '^`.*$'
  rules:
    - length_equal: 2
      formula: "AaAbBaBb"
    - length_equal: 3
      formula: "AaBaCaCb"
    - length_in_range: [4, 14]
      formula: "AaBaCaZa"
...

啊	a
阿	aa
阿坝	aab
# 省略完整的 flypy 字词码表 ...

```

**Comment by dangehub** [comment]
请问这个方案只能造两字词吗？
我两字都是正常造的，但是三字能进入造词流程，也能看到太极符号，但是造完就没了，同样的流程，两字完全正常。

**Comment by pimgeek** [comment]
> 三字能进入造词流程，也能看到太极符号，但是造完就没了，同样的流程，两字完全正常。

不会的，看这段代码就明白，2 字词、3 字词、4 到 10 字词都支持，只是需要前后两次上屏。出现太极图标以后，你按照造词规则重新输入一遍就转正了。三字词的规则就是 首字声母Aa+二字声母Ba+三字声母Ca+三字韵母Cb，这个 A B C 大小写混合的造词模式代码实在有点绕 😅


```yaml
name: flypyzc.extended
version: "0.1"
sort: original
import_tables:
  - flypyzc

encoder:
  exclude_patterns:
    - '^o.*$'
    - '^`.*$'
  rules:
    - length_equal: 2
      formula: "AaAbBaBb"
    - length_equal: 3
      formula: "AaBaCaCb"
    - length_in_range: [4, 10]
      formula: "AaBaCaZa"
...
```

**Comment by dangehub** [comment]
> > 三字能进入造词流程，也能看到太极符号，但是造完就没了，同样的流程，两字完全正常。
> 
> 不会的，看这段代码就明白，2 字词、3 字词、4 到 10 字词都支持，只是需要前后两次上屏。出现太极图标以后，你按照造词规则重新输入一遍就转正了。三字词的规则就是 首字声母Aa+二字声母Ba+三字声母Ca+三字韵母Cb，这个 A B C 大小写混合的造词模式代码实在有点绕 😅
> 
> ```yaml
> name: flypyzc.extended
> version: "0.1"
> sort: original
> import_tables:
>   - flypyzc
> 
> encoder:
>   exclude_patterns:
>     - '^o.*$'
>     - '^`.*$'
>   rules:
>     - length_equal: 2
>       formula: "AaAbBaBb"
>     - length_equal: 3
>       formula: "AaBaCaCb"
>     - length_in_range: [4, 10]
>       formula: "AaBaCaZa"
> ...
> ```



> > 三字能进入造词流程，也能看到太极符号，但是造完就没了，同样的流程，两字完全正常。
> 
> 不会的，看这段代码就明白，2 字词、3 字词、4 到 10 字词都支持，只是需要前后两次上屏。出现太极图标以后，你按照造词规则重新输入一遍就转正了。三字词的规则就是 首字声母Aa+二字声母Ba+三字声母Ca+三字韵母Cb，这个 A B C 大小写混合的造词模式代码实在有点绕 😅
> 
> ```yaml
> name: flypyzc.extended
> version: "0.1"
> sort: original
> import_tables:
>   - flypyzc
> 
> encoder:
>   exclude_patterns:
>     - '^o.*$'
>     - '^`.*$'
>   rules:
>     - length_equal: 2
>       formula: "AaAbBaBb"
>     - length_equal: 3
>       formula: "AaBaCaCb"
>     - length_in_range: [4, 10]
>       formula: "AaBaCaZa"
> ...
> ```

谢谢，我后面自己翻配置文件也明白了，今天上github一看您的解释果然是这样的，不过我更喜欢用直接用前两个字来定位。

感觉rime这种框架，就不适合长段输入，因为没有结合到云词库，光靠自己去造词感觉得不偿失了。词是造不完的，除非靠很多数据来即时更新词库内的权重。
造词功能还是适用于常用的长词，尤其是专业工作者或者写论文这种使用场景。

**Comment by ernsky** [comment]
五笔如何可以实现？

**Comment by pimgeek** [comment]
> 五笔如何可以实现？

上面已经写过 [手动造词的配置方法](https://github.com/ryan00zou/rime-xhup/issues/1#issuecomment-1627603834) 了，五笔也可以做到。

根据 [造词的规则](https://github.com/ryan00zou/rime-xhup/issues/1#issuecomment-1654350098)，三字词的规则是 首字首根Aa+二字首根Ba+三字首根Ca+三字次根Cb；如果希望取第三字的首、末根，需要改为使用这种 rules 写法：

```
  rules:
    - length_equal: 2
      formula: "AaAbBaBb"
    - length_equal: 3
      formula: "AaBaCaCz"
    - length_in_range: [4, 10]
      formula: "AaBaCaZa"
```

除了阅读研究本讨论序列中的造词方法，也可参考 [Rime 官方文档中的说明](https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E9%85%8D%E7%BD%AE)
